sonar.projectKey=marciacrisrs_presencial-app
sonar.organization=marciacrisrs

sonar.host.url=https://sonarcloud.io

sonar.sourceEncoding=UTF-8

sonar.sources=app/src/main
sonar.tests=app/src/test

sonar.java.binaries=app/build

sonar.coverage.exclusions=**/R.class,**/R$*.class,**/BuildConfig.*,**/Manifest*.*
sonar.coverage.jacoco.xmlReportPaths=build/reports/kover/report.xml