naming:
  FunctionNaming:
    active: true
    ignoreAnnotated:
      - 'Composable'

complexity:
  LongParameterList:
    active: true
    functionThreshold: 10
    constructorThreshold: 10
    ignoreDefaultParameters: true
    ignoreAnnotated:
      - 'Composable'
  LongMethod:
    active: true
    threshold: 60
    ignoreAnnotated:
      - 'Composable'
  TooManyFunctions:
    active: true
    thresholdInFiles: 15
    thresholdInClasses: 15
    thresholdInInterfaces: 15
    thresholdInObjects: 15
  CyclomaticComplexMethod:
    active: true
    threshold: 20

style:
  ReturnCount:
    active: true
    max: 5
  MagicNumber:
    active: true
    ignoreNumbers:
      - '-1'
      - '0'
      - '1'
      - '2'
      - '20'
      - '40'
      - '60'
      - '80'
      - '100'
    ignorePropertyDeclaration: true
    ignoreAnnotated:
      - 'Composable'
  MaxLineLength:
    active: true
    maxLineLength: 120
    ignoreAnnotated:
      - 'Composable'

exceptions:
  TooGenericExceptionCaught:
    active: true
  SwallowedException:
    active: true
