name: Android CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: read


jobs:
  quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@eef6142e184e90a55f2e9c303f90b1451e0ca2c3 # v4.2.1
        with:
          fetch-depth: 0

      - name: Setup JDK 17
        uses: actions/setup-java@38af9b20f915cd28f96556e929740523a1d95cf2 # v4.4.0
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Cache SonarCloud packages
        uses: actions/cache@615f698973595bd9c894a4f4f41b370605a1811e # v4.2.1
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Grant execute permission
        run: chmod +x gradlew

      - name: Run Detekt
        run: ./gradlew detekt --stacktrace

      - name: Run Android Lint
        run: ./gradlew lintDebug --stacktrace

      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest --stacktrace

      - name: Generate Coverage Report
        run: ./gradlew koverXmlReport --stacktrace

      - name: SonarCloud
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./gradlew sonar

      - name: Upload Detekt Reports
        if: always()
        uses: actions/upload-artifact@60a1915033c469e74ba91ea4e92f7b88825f42a6 # v4.4.2
        with:
          name: detekt-report
          path: app/build/reports/detekt/**

      - name: Upload Lint Reports
        if: always()
        uses: actions/upload-artifact@60a1915033c469e74ba91ea4e92f7b88825f42a6 # v4.4.2
        with:
          name: lint-report
          path: |
            app/build/reports/lint-results-debug.html
            app/build/reports/lint-results-debug.xml
            app/build/reports/lint-results-debug.sarif

      - name: Upload Coverage Reports
        if: always()
        uses: actions/upload-artifact@60a1915033c469e74ba91ea4e92f7b88825f42a6 # v4.4.2
        with:
          name: kover-report
          path: app/build/reports/kover/**

      - name: Upload Gradle Problems
        if: always()
        uses: actions/upload-artifact@60a1915033c469e74ba91ea4e92f7b88825f42a6 # v4.4.2
        with:
          name: gradle-problems
          path: build/reports/problems/**